vault:
  container_name: vault
  image: dtestops/vault
  volumes:
    - ./vault.hcl:/etc/vault.hcl
  links:
    - "mysql:mysql"
  ports:
    - "8200:8200"
  command: "server -config=/etc/vault.hcl"
  environment:
    - VAULT_ADDR=http://127.0.0.1:8200
mysql:
  container_name: mysql
  image: mysql:5.7
  environment:
    - "MYSQL_ROOT_PASSWORD=secret"